# SportsVista API Configuration
# Replace the placeholders with your actual API keys

# Get your key from https://www.cricapi.com/
cricapi.key=db7e45fa-b899-491f-ae65-eb135564f626

# Get your key from RapidAPI for api-football: https://rapidapi.com/api-sports/api/api-football/
football.rapidapi.key=d6167a7819msh9ffebab8c371583p1a0e7fjsn60c1647ad499

# Get your key from https://www.balldontlie.io/ (Version 1+ needs a key)
nba.balldontlie.key=29d54fa5-88d1-46f3-8908-6c8cf2286abc
